### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by andre68723** [gering/MoneyMoney-CapTrader-Extension#2]
No problem report, just wanted to thank you for providing this great extension

Works like a charm 🙏

(especially - you solved the [currency problem](https://github.com/krambox/moneymoney-ibkr/issues/4))

**Comment by gering** [comment]
Thanks for your feedback. Another [PR](https://github.com/gering/MoneyMoney-CapTrader-Extension/pull/5) for currency handling is on its way.
