### ISSUE TITLE
integration of sub depots

### ISSUE THREAD

**Issue by kochsalz** [gering/MoneyMoney-CapTrader-Extension#3]
Hallo Robert,

ich habe bei Captrader eine Hauptdepot und mehrere Unterdepots.
wenn ich jetzt Captrader über Jodle anbinde, dann überspielt es nur EIN Unterkonto.
Weder das Hauptkonto noch die anderen Unterkonten.
Weisst Du, was ich da falsch mache?

Danke Dir.

Gruß

Andreas

**Comment by gering** [comment]
Hallo Andreas,
leider kenne ich mich mit dieser Konstellation nicht aus. 
Sorry, ich kann nicht helfen.
VG
